"""init

Revision ID: 0001
Revises: 
Create Date: 2026-01-18 21:57:27.660837

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0001'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('permissions',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('name')
    )
    op.create_table('roles',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('name')
    )
    op.create_table('role_permission_association',
    sa.Column('role_name', sa.String(length=255), nullable=False),
    sa.Column('permission_name', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['permission_name'], ['permissions.name'], ),
    sa.ForeignKeyConstraint(['role_name'], ['roles.name'], ),
    sa.PrimaryKeyConstraint('role_name', 'permission_name')
    )
    op.create_table('user',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('hashed_password', sa.String(length=1024), nullable=False),
    sa.Column('role', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['role'], ['roles.name'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_table('link',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('edit_key', sa.String(length=255), nullable=True),
    sa.Column('long', sa.String(length=2048), nullable=False),
    sa.Column('short', sa.String(length=128), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('times_used', sa.Integer(), nullable=False),
    sa.Column('redirect_limit', sa.Integer(), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('NOT (user_id IS NULL AND edit_key IS NULL)', name='user_or_edit_key_required'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_link_edit_key'), 'link', ['edit_key'], unique=True)
    op.create_index(op.f('ix_link_short'), 'link', ['short'], unique=True)
    op.create_table('token',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('access_token', sa.String(length=255), nullable=False),
    sa.Column('refresh_token', sa.String(length=255), nullable=False),
    sa.Column('access_token_expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('refresh_token_expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('access_token'),
    sa.UniqueConstraint('refresh_token')
    )
    op.create_table('click_stamp',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('link_id', sa.UUID(), nullable=False),
    sa.Column('short', sa.String(length=128), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ip', sa.String(length=16), nullable=True),
    sa.Column('user_agent', sa.String(length=1024), nullable=True),
    sa.Column('referer', sa.String(length=2048), nullable=True),
    sa.Column('request_url', sa.String(length=2048), nullable=True),
    sa.ForeignKeyConstraint(['link_id'], ['link.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('click_stamp')
    op.drop_table('token')
    op.drop_index(op.f('ix_link_short'), table_name='link')
    op.drop_index(op.f('ix_link_edit_key'), table_name='link')
    op.drop_table('link')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_table('role_permission_association')
    op.drop_table('roles')
    op.drop_table('permissions')
    # ### end Alembic commands ###
