"""init

Revision ID: 0002
Revises: 0001
Create Date: 2026-01-08 17:16:59.240050

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0002'
down_revision: Union[str, Sequence[str], None] = '0001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('click_stamp',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('link_id', sa.UUID(), nullable=False),
    sa.Column('short', sa.String(length=128), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ip', sa.String(length=16), nullable=True),
    sa.Column('user_agent', sa.String(length=1024), nullable=True),
    sa.Column('referer', sa.String(length=2048), nullable=True),
    sa.Column('request_url', sa.String(length=2048), nullable=True),
    sa.ForeignKeyConstraint(['link_id'], ['link.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('link', 'short',
               existing_type=sa.VARCHAR(length=16),
               type_=sa.String(length=128),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('link', 'short',
               existing_type=sa.String(length=128),
               type_=sa.VARCHAR(length=16),
               existing_nullable=False)
    op.drop_table('click_stamp')
    # ### end Alembic commands ###
