"""role_added

Revision ID: 0003
Revises: 0002
Create Date: 2026-01-08 19:53:18.702919

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0003'
down_revision: Union[str, Sequence[str], None] = '0002'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('roles',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('name')
    )
    op.add_column('user', sa.Column('role', sa.String(length=255), nullable=False))
    op.create_foreign_key(None, 'user', 'roles', ['role'], ['name'])
    op.drop_column('user', 'status')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('status', postgresql.ENUM('ADMIN', 'USER', 'BLOCKED', name='userstatus'), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.drop_column('user', 'role')
    op.drop_table('roles')
    # ### end Alembic commands ###
