"""permissions_added

Revision ID: 0004
Revises: 0003
Create Date: 2026-01-10 20:15:47.500834

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0004'
down_revision: Union[str, Sequence[str], None] = '0003'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('permissions',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('name')
    )
    op.create_table('role_permission_association',
    sa.Column('role_name', sa.String(length=255), nullable=False),
    sa.Column('permission_name', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['permission_name'], ['permissions.name'], ),
    sa.ForeignKeyConstraint(['role_name'], ['roles.name'], ),
    sa.PrimaryKeyConstraint('role_name', 'permission_name')
    )
    # ### end Alembic commands ###


    op.bulk_insert(
        sa.table(
            'permissions',
            sa.column('name', sa.String),
        ),
        [
            {'name': 'manage_links'},
            {'name': 'manage_users'},
        ]
    )

    op.bulk_insert(
        sa.table(
            'role_permission_association',
            sa.column('role_name', sa.String),
            sa.column('permission_name', sa.String)
        ),
        [
            {'role_name': 'admin', 'permission_name': 'manage_links'},
            {'role_name': 'admin', 'permission_name': 'manage_users'},
            {'role_name': 'user', 'permission_name': 'manage_links'},
        ]
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('role_permission_association')
    op.drop_table('permissions')
    # ### end Alembic commands ###
